### ISSUE TITLE
class vcfGenoData does not allow haploid data

### ISSUE THREAD

**Issue by lduvaux** [simonhmartin/genomics_general#1]
Hi,
the documentation says that `popgenWindows.py` can process haploid data from the geno file. However, the `parseVCF.py` does not seem  to deal with haploid vcf (at least I didn't find out how if so).
Therefore one needs to process the data twice using perl during the pipeline what is not very convenient:
```
	# make vcf diploid
perl -pe 's/([01])(:[0-9]*,[0-9:]*,[0-9]*)/$1\|$1$2/g;' -pe 's/.:.:.:.:./.|.:.:.:.:./g;' $vcf.vcf |
	gzip > $vcf.dip.vcf.gz

	# parse vcf
parseVCF.py -i $vcf.dip.vcf.gz --skipIndel --skipMono --minQual 30 --gtf flag=DP min=5 | gzip > $fgeno

	# make vcf haploid again
zcat $fgeno | perl -pe 's/([ATGCN])[\|\/][ATGCN]/$1/g;' | gzip > $fgeno.temp
mv $fgeno.temp $fgeno
```
cheers,
Ludovic

**Comment by simonhmartin** [comment]
Hi,
I have now added support for haploid data, which should automatically detect haploid genotypes in the vcf.
-Simon

**Comment by lduvaux** [comment]
thanks :)

**Comment by javbioUMD** [comment]
Hi, 
I've been trying to run the `popgenWindows.py` script on a haploid geno file, but it  seems there is an issue when invoking the `genomics.py` script. The error I always get is: 


Process Process-1:
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "popgenWindows.py", line 32, in stats_wrapper
    Aln = genomics.genoToAlignment(window.seqDict(), sampleData, genoFormat = genoFormat)
  File "software/genomics_general/genomics_general-master/genomics.py", line 626, in genoToAlignment
    if ploidy is not None: assert len(seqList) == ploidy, "Sample ploidy doesn't match genotype"
AssertionError: Sample ploidy doesn't match genotype

Not sure if the problem is my geno file (sample attached) or the script itself. At any rate I am not getting any calculation. 

The command I used is: 
`python popgenWindows.py-w 10000 -p pops -g all_trans.geno -o all_trans.geno -f haplo`

Cheers,

Javi
[sample.geno.txt](https://github.com/simonhmartin/genomics_general/files/1029842/sample.geno.txt)

**Comment by estolle** [comment]
I got this running after specifying the haploid individuals via "--haploid sample,sample2,sample3,..."
