### ISSUE TITLE
calculate dxy and ABBA,do the input files need to provide invariant sites?

### ISSUE THREAD

**Issue by chelisa** [simonhmartin/genomics_general#122]
Thank you for providing useful and convenient tools to help researchers. Here is a question I would like to ask: When we calculate dxy and ABBA, do the input files need to provide invariant sites?Looking forward to reply and answer, thank you!

**Comment by simonhmartin** [comment]
Apologies for the slow response. For dXY, you do need to have invariant sites in the file. This is because the script for not assume that missing sites are invariant. The method used uses the same unbiased approach as pixy, described here: https://doi.org/10.1111/1755-0998.13326


For ABBA-BABA statistics, you do not need to have invariant sites present, as only SNPs are used.
