### ISSUE TITLE
Why the ABBA, BABA, and D formula are different from MBE 2011 paper

### ISSUE THREAD

**Issue by tonyworld** [simonhmartin/genomics_general#15]
Hi Simon,
I have been using your genomics library to calculate ABBA, BABA and D statistics from four populations. It runs well but I have two issues with the latest script.
1,  I notices in genomics.py. The formulas of ABBA and BABA are different from MBE 2011 publication. It's
(1-p1)*p2*p3*(1-p4) + p1*(1-p2)*(1-p3)*p4
in the script, but 
(1-p1)*p2*p3*(1-p4) in the paper. Why changed it and what's the difference? 
2, I did a few SNPs manually. The D's calculated by ABBABABAwindows.py were equal to the output from D_new function, while in the ABBABABA function it was calculated by the old D function. I couldn't understand how it happened. The code chunk is like,
        _D_ = D(p1,p2,p3,p4)  # I think this is the old D function
        _fd_ = fd(p1,p2,p3,p4)
        _fdm_ = fdm(p1,p2,p3,p4)
        _ABBA_ = ABBA(p1,p2,p3,p4)  # and this is the new ABBA formula
        _BABA_ = BABA(p1,p2,p3,p4)

**Comment by simonhmartin** [comment]
Hi,
Thanks for pointing this out. This is a bug that has crept in as a result of testing new variants of these statistics.
So do you agree that the D value output by the script correctly matched the original D description, but the ABBA and BABA counts are not?
I had personally not detected this because I have been using only sites at which the outgroup is fixed, in which case D_new = D.
I will correct the issue, but for now, you can try my newer script called fourPopWindows.py, which has the option --polarize, to ignore sites where the outgroup is polymorphic. This script outputs a range of statistics that we are still exploring.
