### ISSUE TITLE
strange pi and dxy

### ISSUE THREAD

**Issue by rapamycin** [simonhmartin/genomics_general#22]
I'm calculating windowed pi and dxy within or between close related populations using you scripts. It's strange that the estimated pi and dxy is quite large, such as mean value of 0.1 of pi and 0.2 of dxy. But i know the pi of my populations is about 0.001, and dxy between populations should below               0.01. So, do you have any idea of those strange results? I suspect it may related to the correction of window size, if so, how should i do to get the right value of pi and dxy?

**Comment by simonhmartin** [comment]
The most common cause of this is using an input file with only variant sites. My scripts do not assume that sites missing from the input file are invariant. The invariant sites need to be included to be considered.

**Comment by rapamycin** [comment]
Yes, you are right, I only input variant sites, as a vcf contain all sites is so large, and I think it's quiet common to do like this. To get a window size corrected pi and dxy, can I do like this: assume in a window with length of L and V variant sites, window corrected pi and dxy is pi_window_corrected=pi_raw*V/L and dxy_window_corrected=dxy_raw*V/L?

**Comment by simonhmartin** [comment]
I would not recommend dividing by the total length of the window, because the SNPs you have included contain only those that were successfully genotyped. In most windows there will be many sites that could not have a confident genotype call, due to things like low coverage, repeats etc. This is why I decided to require invariant sites in my scripts.
If this is not feasible, I would recommend trying to determine the number of callable genotypes per window, even if you don't store the full VCF. I know that [GATK 3 has a tool to identify the number of callable loci](https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_coverage_CallableLoci.php), but I am not sure if it has been ported to GATK 4.

**Comment by glaudelrio** [comment]
Hi Simon! Would the fact that your code does not take invariant sites in consideration be a problem if we are only looking at relative measurements? For example, I am looking for peaks of Dxy and pi across scaffolds for individuals in different populations, the absolute values of Dxy and pi are not important for me. Can I still trust the peaks and deeps I am observing with the stats obtained from VCFs without invariant sites?
Thank you so much!

**Comment by simonhmartin** [comment]
Hi! This is a good question, and I think the answer is probably yes.

Just to clarify, my scripts do "take invariant sites in consideration", it's just that those invariant sites need to be present in the vcf to be considered. Invariants that are not actually included as lines with genotypes in the vcf will not be considered because my scripts can't "see" them, and do not blindly assume that missing sites are invariant.

Regarding your question about relative measures: The numerator of pi and dxy will be the same regardless of whether your file includes invariant sites. The deniminator is the the total number of variant and invariant sites present in the window (technically the denominator is recalculated for every pair of individuals because different individuals can have different amounts of missing data). If we assume that the proportion of missing data is about the same for variant and invariant sites, then I think yes, the relative measures of pi and dxy should be approximately the same as if you included the invariants. This would of course be testable using a subset of data with invariants left in or filtered out.

**Comment by glaudelrio** [comment]
Got you! I was trying to avoid invariant sites because the files were too heavy. Thank you for your quick response!
I will make some tests and see how it goes. If the differences are not huge, I will stick with the lighter files.
Thank you so much!
