### ISSUE TITLE
Output sites used

### ISSUE THREAD

**Issue by foala** [simonhmartin/genomics_general#38]
Hi,
Thank you again for the great script. It made my life much easier!
I am wondering if there is a way to output the sites used, i.e. the snps? This would help the downstream analyses of identifying alleles associated a certain trait.

Thank you very much

**Comment by simonhmartin** [comment]
Hi,
None of my window-based scripts currently have this functionality. Which script are you referring to?
It might be best for you to use other tools such as Plink?

**Comment by foala** [comment]
Hi,
Thank you for your reply.
I am using both popgenWindows.py and ABBABABAWindows.py.
I have identified many loci of interest, and I wish there is a way to retrieve the SNPs within for a closer look.

May I know how can I use that in Plink?

Thank you very much,

**Comment by simonhmartin** [comment]
Plink can do many things, including testing whether SNPs are associated with traits, if you have trait variation among your samples. I am not an expert in how to use it though.
For the `popgenWindows.py` script, you could go down to very small windows using something like `--windType sites -w 5`.
This will not work for `ABBABABAwindows.py` though, because that requires at least 100 SNPs per window to give you a reliable result. There is no meaningful  way to quantify the ABBA BABA statistics at a single base level.

**Comment by foala** [comment]
I will try that!
Thank you very much
