### ISSUE TITLE
empty trees --windType coordinate

### ISSUE THREAD

**Issue by kullrich** [simonhmartin/genomics_general#53]
Hi,

using  the coordinate option give not tree output but states that windows were analyzed:

`python genomics_general/phylo/phyml_sliding_windows.py -T 24 -g chr19.phased.PASS.minInd50per.merged.ancestral.geno.gz --prefix chr19.output.phyml_bionj.w25k -w 25000 -S 25000 --windType coordinate --model GTR --optimise n -M 0 -Mi 0 -Ms 50`

`
892 windows queued | 891 results received | 891 results written.
1541 windows queued | 1541 results received | 1540 results written.
2173 windows queued | 2172 results received | 2172 results written.

Writing final results...

2454 windows queued | 2454 results received | 2454 results written.
2454 windows were tested.
2454 results were written.
`

The data files have the correct number of sites per window, however all trees are NA.

`
chr19   3050001 3075000 nan     0       NA
chr19   3075001 3100000 nan     0       NA
chr19   3100001 3125000 3114092 3       NA
chr19   3125001 3150000 3136767 66      NA
chr19   3150001 3175000 3164509 177     NA
chr19   3175001 3200000 3191779 19      NA
chr19   3200001 3225000 3213294 27      NA
chr19   3225001 3250000 3239695 29      NA
chr19   3250001 3275000 3266915 469     NA
chr19   3275001 3300000 3286894 629     NA
`

However, running the same command with **--windType sites** produces phyml trees, which makes me wonder why **--windTypes coordinate** does not.

Thank you in anticipation for your help

I will try to debug.

Best regards

Kristian

**Comment by kullrich** [comment]
OK, using `-M 1 -Mi 1` fixed it.

**Comment by biolevol** [comment]
I'm having the exact same issue I've tried setting -Mi and -M to 1 but nothing seems to work. This is what I'm currently running but the output is still empty 

 python3 genomics_general/phylo/phyml_sliding_windows.py -g OST_O347.Dgua.SNPs.geno.gz --prefix OST_O347_Dgua.phyml_bionj.w250kb -S 250000 -w 250000 --windType coordinate --model GTR --minSNPs 1 -Ms 10  -Mi 1 --optimise n --phyml /usr/bin/phyml --outgroup dgua

**Comment by simonhmartin** [comment]
Hi. I'm not sure what the problem could be. I suggest adding `--log phyml_log.txt` which will record all output from phyml. Also, including option `--test` will cause it to leave all the temporary files in place so you can go and check if they look ok. Note that this option will also cause it to stop running after the first ten windows.

**Comment by biolevol** [comment]
Thank you so much for your quick response. I've tried adding --log phyml_log.txt also including the --test option but the output is still empty and the temporary directories are also empty

**Comment by simonhmartin** [comment]
Ok, so the script is not even making the input files, let alone attempting to run Phyml. That suggests that it is still failing the test of minimum sites per window, despite you setting the minimums to 1. Is it possible that there is an individual in the file that is missing genotypes at all sites in the genome for some reason?
If it's not that, then I suggest you send over a sample of the geno file (e.g. the first 10k lines) and I can try troubleshoot.

**Comment by biolevol** [comment]
Thank you so much for looking into the issue, and my apologies for taking a while to respond. I don't think there is any individual that is missing all genotypes, I have evaluated the percentage for missing sites for every individual, and for every individual the missing sites account for less than 2% of the sites apart from my outgroup that the missing sites account for 6%. Also I forgot to mention that I was able to run popgenWindows.py without any issues. I have attached below the first 10K lines of the geno file (the first positions might have a slightly higher percentage of missingness as they correspond to a region very close to the centromere and we have an over-representation of repetitive sequences so I wouldn't put too much emphasis on those calls. I have added a .txt extension in order to upload it )

Thank you you again 

[OST_O347.Dgua.SNPs.10K.geno.txt](https://github.com/simonhmartin/genomics_general/files/6531680/OST_O347.Dgua.SNPs.10K.geno.txt)
