### ISSUE TITLE
input gff for extractCDSAlignments.py

### ISSUE THREAD

**Issue by MafaldaSFerreira** [simonhmartin/genomics_general#61]
Hello,

I was trying to extract cds sequences from a geno file and the script does not seem to like by gff3 file. I wanted to ask what gff3 file was extractCDSAlignments.py trained with? I am trying to use a gff3 file from Ensembl, and I get an error like this:

`python3 extractCDSAlignments.py --gff Clupea_harengus.Ch_v2.0.2.104.gff3.gz -g gene.p.geno --outFormat fasta`

```
Traceback (most recent call last):
  File "/proj/snic2020-2-19/private/herring/users/mafalda/software/genomics_generals_Ab21/extractCDSAlignments.py", line 43, in <module>
    geneData = genomics.parseGenes(gffLines, targets=args.targets)
  File "/crex/proj/snic2020-2-19/private/herring/users/mafalda/software/genomics_generals_Ab21/genomics.py", line 198, in parseGenes
    output[scaffold][mRNA]['exons'] += 1
KeyError: 'transcript:ENSCHAT00000051843'
```

I wonder if it is because:
1) Due to the notation of Ensembl gff files, where there are ":" like in the Error separating certain elements in the ID field of the gff.
2) I am using a partial geno file just containing a small region in the genome, while my gff file is for the entire genome.

Any help would me much appreciated. 

Thanks
Mafalda

**Comment by simonhmartin** [comment]
Hi Mafalda,
It might be a gff3 format issue, as I have not tested the script on many different types.
However, it might also be related to the fact that you have a reduced gff3 file.
Actually just yesterday I encountered a similar error and in that case the problem was that a CDS was included whose parent mRNA was not present in the file.
To solve the problem, I am planning on adding functionality to the script to specify the genomic region(s) you're interested in, and it will make sure to only consider CDSs for which the whole mRNA is contained within that region.

So I recommend that you first test the script on the complete gff3 to see if it fails again, and if not, then I will try upload the version that allows specification of a region ASAP.
Simon

**Comment by MafaldaSFerreira** [comment]
Thank you Simon!

Actually, I am using a complete (whole-genome) gff3 file from Ensembl but a partial .geno file just containing a region of interest. Does that make sense? So, all the information for genes and transcripts should be there (in theory!). So, the script is failing with the complete gff3. 

Cheers,
Mafalda

**Comment by simonhmartin** [comment]
Hmm - I could not reproduce the error using the first 100 lines.
Looking at the format, I don't think there will be a problem with `ID=transcript:ENSCHAT00000000004`, because the `=` is still there, and everything to the right becomes the mRNA name, which is maybe annoying, but should not break the script.
Importantly, the error you encountered happened on transcript number 51843, which is evidently some way into the gff file, so I think it is more likely that the file is malformed. Specifically, it seems that there are CDS regions defined with `parent=transcript:ENSCHAT00000051843`, but the mRNA with that ID is either absent from the file or occurs after the CDSs in the file, so the script doesn't know about it. I recommend grepping that transcript ID and seeing whether there is a defined mRNA for it.

I have now pushed the updated version of extractCDSalignments.py to github. A few things to note:
- I decided to add functionality to read gtf format at the same time, so the annotation file is now defined using `--annotation` rather than `--gff`.
- You can specify the region(s) of interest using `--regions "1:10001-20000"`, which would only extract genes on chromosome 1 between positions 10,001 and 20,000.
- You will need to also have the latest version of genomics.py for this to work.

**Comment by MafaldaSFerreira** [comment]
You are right; there is some weird formatting issue for that particular region and the transcript/mRNA is absent... Ensembl also offers _.gtf_ files, so I tried that and everything seems to be working! (thank you for adding the `--annotation` `--annotationFormat` and `--regions` options). I have been playing with this this morning and I noticed a few other things that might be worth mentioning in the header of the script. Mainly, I noticed the script doesn't work if the _.geno_ is not bgzipped and indexed.

So, here is a summary of what I did:

- I first ran my _.geno_ through _filterGenotypes.py_ to make sure it was in the `phased` format, as instructed in the script.
- I had to bgzip the _.geno_ using `bgzip ENSCHAG00000022133.p.geno` and generate a _.tbi_ index using `tabix -p vcf bgzip ENSCHAG00000022133.p.geno.gz` for it to work, because otherwise I would get an error like this:

```
Parsing gene data
Extracting 3 gene sequences from 10
    Extracting mRNA "ENSCHAT00000051903": 10:25123881-25126178, 4 exons
[E::idx_find_and_load] Could not retrieve index file for 'ENSCHAG00000022133.p.geno.gz'
Could not load .tbi/.csi index of ENSCHAG00000022133.p.geno.gz: No such file or directory
[E::idx_find_and_load] Could not retrieve index file for 'ENSCHAG00000022133.p.geno.gz'
Could not load .tbi/.csi index of ENSCHAG00000022133.p.geno.gz: No such file or directory
[E::idx_find_and_load] Could not retrieve index file for 'ENSCHAG00000022133.p.geno.gz'
Could not load .tbi/.csi index of ENSCHAG00000022133.p.geno.gz: No such file or directory
[E::idx_find_and_load] Could not retrieve index file for 'ENSCHAG00000022133.p.geno.gz'
Could not load .tbi/.csi index of ENSCHAG00000022133.p.geno.gz: No such file or directory
Traceback (most recent call last):
  File "/proj/snic2020-2-19/private/herring/users/mafalda/software/genomics_generals_Oct21/extractCDSAlignments.py", line 140, in <module>
    alnString = genomics.makeAlnString(outputNames,cdsSeqs,outFormat=args.outFormat, lineLen=None)
  File "/crex/proj/snic2020-2-19/private/herring/users/mafalda/software/genomics_generals_Oct21/genomics.py", line 2177, in makeAlnString
    seqLen = max([len(seq) for seq in seqs])
ValueError: max() arg is an empty sequence
```

- the `-p vcf` flag in the `tabix` command was important, otherwise I got sequences just containing missing data (probably the _.tbi_ was poorly formatted).

Again, thank you for providing these amazing tools Simon!
Cheers
Mafalda

**Comment by simonhmartin** [comment]
Great. Thanks Mafalda - I think I will add a whole entry to the README file to explain these steps.
Simon
