### ISSUE TITLE
parseVCF.py error

### ISSUE THREAD

**Issue by EmilyPhelps** [simonhmartin/genomics_general#89]
Hello, i am getting the error below:
```
Traceback (most recent call last):
  File "/local/chh20csu/genomics_general/VCF_processing/parseVCF.py", line 375, in <module>
    output = vcfSite.getGenotypes(gtFilters,asList=True,withPhase=True,samples=samples,missing=args.missing,
  File "/local/chh20csu/genomics_general/VCF_processing/parseVCF.py", line 174, in getGenotypes
    output[sample] = self.getGenotype(sample, gtFilters=gtFilters, withPhase=withPhase, asNumbers=asNumbers,
  File "/local/chh20csu/genomics_general/VCF_processing/parseVCF.py", line 134, in getGenotype
    elif ploidy != len(genoData["alleles"]):
KeyError: 'alleles'
```

My VCF is generated by ANGSD and looks like this 

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	AL13_BLST.bam	AL2_BLST.bam	AL4_BLST.bam	UO03_R_BLST.bam	AL10_STRI.bamAL11_STRI.bam	AL1_STRI.bam	AL3_STRI.bam	AL5_STRI.bam	AL6_STRI.bam	AL7_STRI.bam	AL8_STRI.bam	AL9_STRI.bam	U0_06_STRI.bam	UO_05_STRI.bam
scaffold1	404	.	T	A	0	PASS	NS=7;DP=14;AF=0.285319	DP:GL:PL:GP	.:.:.:.	.:.:.:.	.:.:.:.	.:.:.:.	2:-3.57546,0,-2.37417:36,0,24:0.00033249,0.998825,0.000842372	1:-4.17703,-0.301001,0:42,3,0:0.000119066,0.71461,0.285271	3:-3.27403,-3.87603,-11.6281:33,39,116:0.833584,0.166416,5.87917e-10	3:0,-0.902143,-10.1285:0,9,101:0.909071,0.0909291,1.07772e-11	2:-3.57503,0,-3.57503:36,0,36:0.000333083,0.999614,5.3087e-05	1:0,-0.301001,-4.17703:0,3,42:0.714662,0.28533,7.57709e-06	0:0,0,0:0,0,0:0.333333,0.333333,0.333333	0:0,0,0:0,0,0:0.333333,0.333333,0.333333	0:0,0,0:0,0,0:0.333333,0.333333,0.333333	0:0,0,0:0,0,0:0.333333,0.333333,0.333333	2:0,-0.602002,-8.35407:0,6,84:0.833584,0.166416,5.87917e-10
```
Im pretty new to python but generally competent in bash.  My ultimate goal is to do Max SNP windows for Fst.

**Comment by simonhmartin** [comment]
Hi Emily,
Thanks for including your VCF in the question!
The problem is that your file lacks the `GT` field for each individual, which is the called (most likely) genotype. The `FORMAT` column lists all the fields included in the file, which in your case are `DP:GL:PL:GP`. Typically users of ANGSD don't use genotype calls because they use probabilistic software that incorporates genotype uncertainty, but my scripts need called genotypes. I don't know if ANGSD has an option to call the most likely genotype, but other tools exist to do this. For example, `bcftools call` will add a `GT` field for the most likely genotype by considering the posterior likelihoods (`PL` field).
Simon

**Comment by EmilyPhelps** [comment]
Hi Simon,

Thanks for the quick reply! I have managed to solve this issue thanks to your help.

In Angsd you can call the most likely genotypes with the -doGeno flag. I previously had set it to "1" but actually whilst this calls the GT it does not include them in the BCF. So I set this to "2" and got the GT field. After converting to a VCF this was fed int your parseVCF.py program and worked perfectly!

Thought I would post my full solution incase anyone had a similar issue in future.

Thanks for the great tool!

**Comment by wuyh0328** [comment]
> Hi Emily,
Hi Emily, I have the same problem as you. Can you share your solution? Thank you so much 1! With best wishes!
